name: flutter_mapbox_navigation
description: >
  Add Turn By Turn Navigation to Your Flutter Application Using MapBox. 
  Never leave your app when you need to navigate your users to a location.
version: 0.1.9
homepage: "https://www.eopeter.com"
repository: "https://github.com/eopeter/flutter_mapbox_navigation"

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  freezed: ^2.3.5
  freezed_annotation: ^2.2.0
  plugin_platform_interface: ^2.1.5
  very_good_analysis: ^5.0.0+1

dev_dependencies:
  build_runner: ^2.4.6
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  json_serializable:

flutter:
  plugin:
    platforms:
      android:
        package: com.eopeter.fluttermapboxnavigation
        pluginClass: FlutterMapboxNavigationPlugin
      ios:
        pluginClass: FlutterMapboxNavigationPlugin
  #      linux:
  #        pluginClass: FlutterMapboxNavigationPlugin
  #      macos:
  #        pluginClass: FlutterMapboxNavigationPlugin
  #      windows:
  #        pluginClass: FlutterMapboxNavigationPluginCApi
  #      web:
  #        pluginClass: FlutterMapboxNavigationWeb
  #        fileName: flutter_mapbox_navigation_web.dart
